config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do 
  	member do
  		get 'like',to: 'posts#like',as: 'like_post'
  		get 'unlike',to: 'posts#unlike',as: 'unlike_post'
  	end
  end

  get ':username/follow', to: 'posts#follow',as: 'follow_user'
  get ':username/unfollow', to: 'posts#unfollow',as: 'unfollow_user'

  get 'pages/index'
  root 'pages#index'
  
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	acts_as_likeable
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts

  def self.find_for_database_authentication(warden_conditions)
	conditions = warden_conditions.dup
	if login = conditions.delete(:login)
	  where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	else
	  where(conditions.to_h).first
	end
  end

  has_attached_file :avatar, :styles => { :large => "300x300#",medium: "40x40", :thumb => "30x30#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }

  acts_as_followable
  acts_as_follower
  acts_as_liker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar,:username, :email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_in_path_for(resource)
    posts_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy,:like,:unlike]

  def index
    @posts = Post.all
  end

  def show
    
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      respond_to do |format|
        format.html{redirect_to posts_path}
        format.js{}
      end
    else
      redirect_to :back,flash[:notice]="Post could not be created."
    end
    redirect_to posts_path
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    if @post.user_id = current_user.id
      @post.destroy
      respond_to do |format|
        format.html{redirect_to :back}
        format.js{}
      end
    else
      redirect_to :back,flash[:notice]="Unauthorized action"
    end
  end

  def like
    if !current_user.likes?(@post)
      current_user.like!(@post)
      respond_to do |format|
        format.html{redirect_to :back}
        format.js{}
      end
    else
      redirect_to :back,flash[:notice]="You already liked this post"
    end
  end

  def unlike
    if current_user.likes?(@post)
      current_user.unlike!(@post)
      respond_to do |format|
        format.html{redirect_to :back}
        format.js{}
      end
    else
      redirect_to :back,flash[:notice]="You haven't liked this post"
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!5
%html
	%head
		%title Blog
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		%nav.nav.navbar-default.navbar-fixed-top
			.container-fluid
				.navbar-header
					= link_to "Blog",root_path,class: 'navbar-brand'
				- if user_signed_in?
					%ul.nav.navbar-nav
						%li= link_to "Home",root_path
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "Sign Out",destroy_user_session_path,method: :delete
				-else
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "Sign In",new_user_session_path
						%li= link_to "Sign Up",new_user_registration_path

		- if !notice.blank?
			.notice= notice
		- elsif !alert.blank?
			.alert= alert

		= yield

app/views/pages/index.html.haml
#welcomeContainer
	Welcome to blogBlog, A simple blogging application

		

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_post.html.haml
.post{data:{id: post.id}}
	.postHeader
		= image_tag(post.user.avatar.url(:thumb),class: 'img-circle')
		= post.user.username
	.postBody
		%h3= post.title
		%p= post.content
	.postFooter
		- if post.liked_by?(current_user)
			= link_to "Dislike","#",class: 'unlike-btn btn-danger',onclick: 'UnlikePost("#{post.id}")'
		- else
			= link_to "Like","#",class: 'like-btn btn-default',onclick: 'LikePost("#{post.id}")'

app/views/posts/create.js.erb
$('#feedArea').prepend('<%= j(render @post) %>')

app/views/posts/destroy.js.erb
$('.post[data-id=<%= @post.id %>]').slideUp('slow').remove();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
#mainContainer
  .row
    .col-xs-4.col-sm-3.col-md-3.col-lg-3
      #verticleNavigation
        %ul.nav.nav.tabs
          %li= link_to "Home",posts_path
          %li= link_to "New Post",new_post_path
          %li= link_to "Account",edit_user_registration_path
          %li= link_to "Profile"
          %li= link_to "Sign out",destroy_user_session_path,method: :delete
    .col-xs-8.col-sm-8.col-md-8.col-lg-8
      #feedArea
        - if !@posts.blank?
          = render partial: 'post',collection: @posts

app/views/posts/like.js.erb
$('like-btn[data-id=<%= @post.id %>]').removeClass('like-btn btn-default').addClass('unlike-btn btn-danger').attr('onclick','UnlikePost(<%= @post.id %>)');

app/views/posts/new.html.erb
<div class="form">
	<h2>New Post</h1>
	<hr/>
	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.haml
#mainContainer
	#post
		%h3= @post.title
		%hr
		%p= @post.content

app/views/posts/unlike.js.erb
$('unlike-btn[data-id=<%= @post.id %>]').removeClass('unlike-btn btn-danger').addClass('like-btn btn-default').attr('onclick','LikePost(<%= @post.id %>)');